/// Flutter icons Cywoodsapp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Cywoodsapp
///      fonts:
///       - asset: fonts/Cywoodsapp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Cywoodsapp {
  Cywoodsapp._();

  static const _kFontFam = 'Cywoodsapp';

  static const IconData american_football_ball = const IconData(0xe800, fontFamily: _kFontFam);
}
